# https://goreleaser.com
project_name: autoscan

# Build
builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
      - windows
    main: ./cmd/autoscan
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X "main.Version={{ .Version }}"
      - -X "main.GitCommit={{ .ShortCommit }}"
      - -X "main.Timestamp={{ .Timestamp }}"
    flags:
      - -trimpath
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm64

# MacOS Universal Binaries
universal_binaries:
  -
    replace: true

# Archive
archives:
  -
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: "binary"

# Checksum
checksum:
  name_template: "checksums.txt"
  algorithm: sha512

# Snapshot
snapshot:
  name_template: "{{ .Major }}.{{ .Minor }}.{{ .Patch }}-dev+{{ .Branch  }}"

# Changelog
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Merge branch"

# Docker
dockers:
- image_templates:
  - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:latest"
  - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Tag }}"
  - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Major }}"
  use: buildx
  dockerfile: ./apps/autoscan/Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:latest"
  - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Tag }}"
  - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Major }}"
  use: buildx
  goarch: arm64
  dockerfile: ./apps/autoscan/Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64"
docker_manifests:
- name_template: "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Version }}"
  image_templates:
  - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Version }}-amd64"
  - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Version }}-arm64"